version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nzos
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dzos
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
  db:
    image: postgres:latest
    container_name: pzos
    volumes:
      - /var/lib/postgresql/data
