# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200)),
                ('dvf', models.CharField(blank=True, choices=[('desirability', 'Desirability'), ('viability', 'Viability'), ('feasibility', 'Feasibility')], max_length=200)),
                ('metric', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('On Track', 'On Track'), ('Delayed', 'Delayed'), ('At Risk', 'At Risk')], max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='assumption',
            name='status',
            field=models.CharField(blank=True, choices=[('Validated', 'Validated'), ('In Progress', 'In Progress'), ('Invalidated', 'Invalidated'), ('Inconclusive', 'Inconclusive')], max_length=200),
        ),
    ]
