# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-10 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181010_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='stage',
        ),
    ]
