# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_future_past_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumption',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
        migrations.AddField(
            model_name='future',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
        migrations.AddField(
            model_name='metric',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
        migrations.AddField(
            model_name='past',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
        migrations.AddField(
            model_name='solution',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
        migrations.AddField(
            model_name='summary',
            name='stage',
            field=models.CharField(blank=True, choices=[('seed', 'Seed'), ('seedlaunch', 'Seed Launch'), ('launch', 'Launch')], max_length=200),
        ),
    ]
