# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumption',
            name='learnings',
            field=models.TextField(blank=True),
        ),
    ]
