# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20180921_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y%m%d'),
        ),
    ]
