# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20180923_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='permission',
            field=models.CharField(blank=True, choices=[('edit', 'Edit'), ('view', 'View')], max_length=200),
        ),
    ]
