# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_team_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, choices=[('Concept', 'Concept'), ('Seed 1', 'Seed 1'), ('Seed 2', 'Seed 2'), ('Seed 3', 'Seed 3'), ('Launch 1', 'Launch 1'), ('Launch 2', 'Launch 2'), ('Scale', 'Scale')], max_length=200),
        ),
    ]
