# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0021_dvf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zx_dashboard', models.BooleanField(default=False)),
                ('os_model', models.BooleanField(default=False)),
                ('assumptions', models.BooleanField(default=False)),
                ('elevator_pitch', models.BooleanField(default=False)),
                ('Problem', models.BooleanField(default=False)),
                ('solution', models.BooleanField(default=False)),
                ('business_model', models.BooleanField(default=False)),
                ('checkpoint', models.BooleanField(default=False)),
                ('assumption_list', models.BooleanField(default=False)),
                ('traction', models.BooleanField(default=False)),
                ('dashboard', models.BooleanField(default=False)),
                ('next_steps', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
