# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='Problem',
            new_name='problem',
        ),
    ]
